data:
  train_files: /mnt/ai4sci_develop_hz/sicong/EasyR1/data/hiyouga/geometry3k@train
  val_files: /mnt/ai4sci_develop_hz/sicong/EasyR1/data/hiyouga/geometry3k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 2048
  max_response_length: 4096
  rollout_batch_size: 128
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 64
    micro_batch_size_per_device_for_update: 2
    micro_batch_size_per_device_for_experience: 2
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 1.0e-2
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /mnt/ai4sci_develop_hz/sicong/checkpoints/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    temperature: 1.0
    n: 5
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    compute_score: openr1
    batch_processing: true

trainer:
  total_episodes: 15
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: lmm_as_judge_debug
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: 5
  val_before_train: true
  val_only: false
  val_generations_to_log: 1
  save_freq: 5
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: null
  load_checkpoint_path: null
